In [1]:
import numpy as np
a=np.array([1,2,3])
print("type: %s" %type(a))
print("shape: %s" %a.shape)
print(a[0],a[1],a[2])
a[0]=7
print(a)

type: <class 'numpy.ndarray'>
shape: 3
1 2 3
[7 2 3]


In [2]:
b=np.array([[1,2,3],[4,5,6]])
print("shape of b:",b.shape)
print(b[0,0],b[0,1],b[1,0])

shape of b: (2, 3)
1 2 4


In [3]:
a=np.zeros((2,2)) 
print("All zeros matrix: %s" %a)

All zeros matrix: [[0. 0.]
 [0. 0.]]


In [4]:
a=np.ones((2,2)) 
print("All zeros matrix: %s" %a)

All zeros matrix: [[1. 1.]
 [1. 1.]]


In [5]:
d=np.eye(2) #eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
print("identify matrix: %s" %d)

identify matrix: [[1. 0.]
 [0. 1.]]


In [6]:
e=np.random.random((2,2)) #Return random floats of two dimensions
print("Random matrix: %s" %e)

Random matrix: [[0.55150622 0.92157778]
 [0.56552125 0.69599611]]


In [7]:
print("Vectorized sum")
x=np.array([[1,2],[3,4]])
print("x:%s"%x)
print("Sum of x:%s" %np.sum(x))
print("Sum axis=0 %s" %np.sum(x,axis=0))
print("Sum axis=1 %s" %np.sum(x,axis=1))

Vectorized sum
x:[[1 2]
 [3 4]]
Sum of x:10
Sum axis=0 [4 6]
Sum axis=1 [3 7]


In [9]:
a=np.arange(10000)
b=np.arange(10000)
dp=np.dot(a,b)
print("Dot product:%s" %dp)

Dot product:-1724114088


In [10]:
op=np.outer(a,b)
print("Outer product:%s" %op)

Outer product:[[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]
